all: 
  gcc -ggdb -Werror -pg -Wextra -std=gnu11 -Wno-unused-result -mglibc -Wuninitialized -march=x86-64 -Wpedantic -Wall -o vinicius_messias_t4_b2_inducao_repeticao vinicius_messias_t4_b2_inducao_repeticao.c

clean: 
  rm -vf vinicius_messias_t4_b2_inducao_repeticao